import './globals.css';
import Header from '../components/Header';
import Hydration from '@/state/hydration';

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Hydration />
        <main>{children}</main>
      </body>
    </html>
  );
}
